// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhgSiJ1myQRgZXw9m54eF0B1xHC6awuho',
    appId: '1:725003381081:web:15b2b8b0cd2bca98f54448',
    messagingSenderId: '725003381081',
    projectId: 'selon-2ac18',
    authDomain: 'selon-2ac18.firebaseapp.com',
    storageBucket: 'selon-2ac18.appspot.com',
    measurementId: 'G-KMT7X9S54K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxirzd3OwKB0JZATTqyfiB2P8trJ8q6nI',
    appId: '1:725003381081:android:5a42651617d72144f54448',
    messagingSenderId: '725003381081',
    projectId: 'selon-2ac18',
    storageBucket: 'selon-2ac18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc_BO09DYBEXkz4pwGbXxgJVVNIUoJxJE',
    appId: '1:725003381081:ios:2be2a139a431da90f54448',
    messagingSenderId: '725003381081',
    projectId: 'selon-2ac18',
    storageBucket: 'selon-2ac18.appspot.com',
    iosBundleId: 'com.test.loopyFriends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc_BO09DYBEXkz4pwGbXxgJVVNIUoJxJE',
    appId: '1:725003381081:ios:2be2a139a431da90f54448',
    messagingSenderId: '725003381081',
    projectId: 'selon-2ac18',
    storageBucket: 'selon-2ac18.appspot.com',
    iosBundleId: 'com.test.loopyFriends',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhgSiJ1myQRgZXw9m54eF0B1xHC6awuho',
    appId: '1:725003381081:web:1a1353c0380ab48ef54448',
    messagingSenderId: '725003381081',
    projectId: 'selon-2ac18',
    authDomain: 'selon-2ac18.firebaseapp.com',
    storageBucket: 'selon-2ac18.appspot.com',
    measurementId: 'G-HXH7KP5YV2',
  );
}
